# age1=int(input("enter your age1: "))
# age2=int(input("enter your age2: "))
# age3=int(input("enter your age3: "))
# print("oldest among is: ",max(age1,age2,age3))
# print("youngest among is: ",min(age1,age2,age3))